name: mtgml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - boto3
  - aws-xray-sdk
  - elasticsearch
  - stripe
  - pyarrow
  - requests
  - pandas
  - numpy
  - s3fs
  - tensorflow
  - scikit-learn
  - jupyterlab
  - matplotlib
  - pytest
  - coverage
  - pip
  - pip:
    - requests_aws4auth
    - spark-nlp==2.4.5
    - pyspark==2.4.4
